[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor = "H2J7ji6Ki844eJ96C2cJxYCVrDo1GBxmmTt7f2t286eM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/pp/.config/solana/id.json"

[scripts]
test = "bun run ts-mocha -R spec -p ./tsconfig.json -t 1000000 tests/**/*.ts"
